### ISSUE TITLE
Doesnt seem to begin querying devices at all

### ISSUE THREAD

**Issue by ndom91** [minitriga/axians-netbox-plugin-pdu#12]
I can't seem to get this plugin to begin querying my SNMP devices.

I've installed the plugin and setup the worker - I double checked by manually executing `python manage.py pduscheduler`.

I also added a PDUConfig via the web interface to an APC PDU device type I have a few instances of, I double checked the OID via snmpwalk as well, that is valid too. It's read community is also 'public', just like the default for the plugin. These instances also all have primary IPs assigned to their network interfaces. 

I can see my PDU configs via the api endpoint btw, but i have a count of 0 when read via `/api/plugins/pdu/pdu-status/`. 

Am I missing anything else? The `netbox-pdu` systemd service only outputs 'Registering birth', so it seems to have started fine.

**Comment by minitriga** [comment]
Hello, would you be willing to join a call with me later so that we can investigate this?

If you're on the NTC slack please send me your username and I'll get in touch.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ndom91** [comment]
Yeah thanks a lot for the offer! I just joined the ntc slack, my username is `ndom91`. Thanks!

**Comment by minitriga** [comment]
Adding .0 to the end of SNMP String fixed this issue.
